name: 构建多平台exe/app

on:
  push:
    tags:
      - 'v*'  # 当推送标签时触发，如 v1.0.0
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            extension: .exe
            build_script: build_windows.py
          - os: macos-latest
            name: macOS
            extension: .app
            build_script: build_mac.py

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 安装依赖 (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller

    - name: 安装依赖 (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller

    - name: 构建应用
      run: python ${{ matrix.build_script }}

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: 学生管理系统-${{ matrix.name }}
        path: dist/
        retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4

    - name: 创建发布
      uses: softprops/action-gh-release@v2
      with:
        files: '**/*'
        body: |
          ## 学生管理系统 ${{ github.ref_name }}
          
          ### 新功能
          - 学生信息管理
          - 成绩录入与统计
          - 数据持久化存储
          
          ### 下载说明
          - **Windows用户**: 下载 `StudentManagementSystem.exe` 文件
          - **Mac用户**: 下载 `学生管理系统.app` 文件
          
          ### 使用说明
          直接双击运行，无需安装Python环境。
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 